### ISSUE TITLE
GitHub pull requests with the remote branches

### ISSUE THREAD

**Issue by jtarchie** [concourse/git-resource#100]
With remote branches from GitHub the git resource could support pull requests.

I'd like to retire the PR resource. It is becoming a bad fork of the git resource, but without all its features. Like depth, gpg, etc.

Reference: https://gist.github.com/piscisaureus/3342247

Would you accept a PR for this feature? Each PR would report it's SHA as a version.

**Comment by darwin67** [comment]
would love this to be done so i can actually use git-lfs repos in pull requests

**Comment by chendrix** [comment]
Closing because hopefully we come up with something that benefits everyone in concourse/concourse#1172
