### ISSUE TITLE
LFS files not cached

### ISSUE THREAD

**Issue by tinygrasshopper** [concourse/git-resource#101]
We have a repository with files checked in with git-LFS. We notice that these files are not cached, and being fetched on each build run.

Should the git-lfs files be cached by baggage claim.

cc: @henryaj

**Comment by vito** [comment]
Hm, they are cached no differently from the rest of the repo. If they're being fetched that means the entire resource was not cached, not just LFS - we don't even create a container or run the script for a cache hit. Maybe it picked a different worker which didn't have the cache?

**Comment by tinygrasshopper** [comment]
@vito Maybe I am misunderstanding the intended behaviour. 

What we can observe is, when we change a non lfs file in the repository with git-lfs, all the lfs files are refetched, even if they have not changed. Is that intended?

**Comment by tinygrasshopper** [comment]
@chendrix was this issue fixed recently or was this closed on inactivity?

**Comment by chendrix** [comment]
Nope, it was closed because what you stated is the appropriate behavior.

The resource doesn't care know or care whether or not the LFS files have changed independently of the non-LFS files. It treats the entire repository as a single resource and fetches the new version of it.
