### ISSUE TITLE
`get.params.fetch` is undocumented

### ISSUE THREAD

**Issue by ljfranklin** [concourse/git-resource#106]
At a glance, it looks like `get` supports a [`fetch` param](https://github.com/concourse/git-resource/blob/86466108de7332025d0675d7b5b18fbc468fb206/assets/in#L34) that allows additional branches to be fetched. But I don't see this field documented in the README. Doc bug?

**Comment by vito** [comment]
It was [deprecated a while back](https://github.com/concourse/git-resource/commit/1402e57f56d8ec55e4e7696269b77747f27cacc5) and shouldn't be used.

**Comment by ljfranklin** [comment]
@vito thanks unfortunate. My use case is to manually create a merge commit (e.g. merge develop into master, non-fast-forward) and push that commit in CI. Is there a way to do this with tasks using the `git-resource` to pull and push?

**Comment by vito** [comment]
I would just have an explicit resource for each branch, then merge them in a task by adding the other as a remote. See https://github.com/concourse/concourse/blob/master/ci/scripts/master-merge

**Comment by ljfranklin** [comment]
Cool, thanks for the example! I'll also keep an eye on the request for merge commits: https://github.com/concourse/git-resource/issues/96.
