### ISSUE TITLE
support for remote-tracking submodules 

### ISSUE THREAD

**Issue by syslxg** [concourse/git-resource#113]
tldr: we need --remote flag in https://github.com/concourse/git-resource/blob/master/assets/in#L97

this is a new feature in git 1.8.2
http://stackoverflow.com/questions/9189575/git-submodule-tracking-latest
https://git-scm.com/docs/git-submodule

After I switch a sha1 based submodule to remote-tracking submodule, concourse git resource still gives me the submodule at the last SHA1 which supper project recorded, instead of latest of remote branch

**Comment by jtarchie** [comment]
@syslxg, this could cause some issues with versioning in concourse. The `--update` would always get `HEAD` of the remote repos, but leave the `.gitmodules` in dirty state. This should be a workflow that the developers do, not the CI.
