### ISSUE TITLE
Not triggering on a merge commit, or not triggering after branch config change

### ISSUE THREAD

**Issue by squeedee** [concourse/git-resource#12]
Using BDD style description, because it's what I know. 

## Given
I have a branch called `foo`
Foo is a feature branch off `develop`
My git resource is configured as `branch: foo`
The last check of my git resource pointed to sha `aaa`

## When
I merged `foo` to `develop` as a merging commit - creating sha `bbb`
And pushed `develop` to github
And updated my git resource config to `branch: develop`
And `fly configure`d concourse

## Then 
My git resource never triggered with `bbb` 
And I waited a long time

## When
I commited another change to `develop` - creating sha `ccc`

## Then
My git resource triggered with `ccc`
And never showed `bbb`

**Comment by squeedee** [comment]
Hey folks!

Similar issue, when i merge to develop, the git resource (which has `branch: develop`) shows the latest sha as the branch-parent from the merge.. EG:

```
0---1---2-------------6---
         \           /
          --3--4--5--
```

Resource shows '5' not '6'.

**Comment by vito** [comment]
This should be fixed now.
