### ISSUE TITLE
paths parameter does not correctly deal with ** glob patterns

### ISSUE THREAD

**Issue by philwebb** [concourse/git-resource#120]
When trying to use the following `paths` pattern the `check` script sometimes returns the wrong commit:

```yml
      paths:
        - "**/pom.xml
```

I think this has something to do with the way that glob patterns are being expanded in the script. You can replicate the issue by jumping into the docker image and running the following

```
git clone https://github.com/philwebb/spring-boot
cd spring-boot
git checkout concourse-glob-issue
```

To simulate the existing script:
```
paths_search="-- **/pom.xml" && git log --name-only $paths_search
```

You should see `07fb9f233b71b99587c4a5152d392edb39b7b4b6`

To get the actual expected commit:
```
paths_search="**/pom.xml" && git log --name-only -- "$paths_search"
```

You should see `b55868650b1ed199f4fb64fb048f83799b3ad678`

My best guess is you need to change [this line](https://github.com/concourse/git-resource/blob/096e9228292cf0342a8b748b8cf34ecc3edb6cc0/assets/check#L81) to end `-- "$paths_search"` and then remove `--` from [here](https://github.com/concourse/git-resource/blob/096e9228292cf0342a8b748b8cf34ecc3edb6cc0/assets/check#L63)

**Comment by ThibaultDelaune-pro** [comment]
I have a similar issue with glob patterns.

I try to exclude every markdown file with this:
```
ignore_paths:
- "**/*.md"
```
... but it doesn't work (jobs are still triggering when I update my readme files)!

Any idea/suggestion?

_Concourse v.7.4.0_
