### ISSUE TITLE
Excessive Git Clones

### ISSUE THREAD

**Issue by iswix-llc** [concourse/git-resource#132]
I have a simple generic pipeline that gets from 3 repos (1 source triggered 2 scripts/version  not triggered ) and outputs to 1 repos (version).  This pipeline yaml is then used by 16 pipelines. (8 products x 2branches).  The result is my github enterprise server is reporting over 60,000 clones per day.

Is there a way to optimize this?

**Comment by jtarchie** [comment]
I think this might be related to concourse/concourse#1475

**Comment by jtarchie** [comment]
@iswix-llc, there could be two different causes for this:

1. The `check` feature has to do initial `git clone` and `git fetch` every minute to get the latest commits.
2. It could be also related to the caching being cleaned up to [aggressively](https://github.com/concourse/concourse/issues/1510).

To resolve [1], you can try the [webhook](http://concourse.ci/single-page.html#webhook_token) feature. Then you can set `check_every` on the resource to be a large number so concourse is not aggressive on polling for new versions.

**Comment by iswix-llc** [comment]
I have implemented web_hook but that's giving me different issues.  For a new pipeline with three resources:

source - check every24h + webhook   + trigger  (the actual source for the compile)
scripts - check every 24h   (common build support scripts)
version - check every 24 h  ( semver storage )

When I push to source the webhook delivers the message and the source resource shows the ref in the check but the job isn't triggered.   If I manually run the build it greens up.  If I do another push the trigger works and the build greens up.

**Comment by jtarchie** [comment]
Has your issues been resolved with the changes in #147?

**Comment by iswix-llc** [comment]
Yes. A whole host of other problems now but not this one.
