### ISSUE TITLE
Can 'clone --single-branch' be configurable?

### ISSUE THREAD

**Issue by Kiemes** [concourse/git-resource#134]
We just had the need to compare our resource to another branch in the same repository.
```
$(git branch master --contains $(git rev-parse origin/auto-update))
```
'master' is the branch configured in the resource.

This was not possible, because the git-resource only does an '[clone --single-branch](https://github.com/concourse/git-resource/blob/master/assets/in#L59)'

We had to make git aware of the additional branch first (git fetch origin auto-update:refs/remotes/origin/auto-update)

Do you think it would be a good idea of making the '--single-branch' configurable, maybe keep it as default, but still allow for more branches to be fetched?

**Comment by jtarchie** [comment]
@Kiemes, a few reasons this is not done:

* the size of the repo get's larger when pulling down multiple branches
* the branches will not always be latest, just the time of the checkout of `master` versioned

**Comment by Kiemes** [comment]
@jtarchie I thought so as well and agree to all of the reasons for the default behaviour.

But we now had to do this step of fetching more branches anyhow.
What we have in mind is not pulling more branches, but only make git aware of them. This is only some bytes for the git refs and will not pull any content. 

It would just be really convenient if the git-resource would support the fetching of additional branches as an optional configuration.

**Comment by JohnAJimenez** [comment]
I second this request.  If nothing more than being able to get the git log range between the branches. 
Example!:
If I want the commits for just my current branch I should be able to run `git log master.. ` but, because of the single branch, the command errors saying that master is unknown.

**Comment by jtarchie** [comment]
@Kiemes, we are not going to add this feature as we already [deprecated](https://github.com/concourse/git-resource/issues/136) it.

The issue really comes down to how concourse uses versions and caching. When a resource is `git clone`d it is cached with the key related to that SHA. If we add the fetch of other branches in there, they will cached at that point in time. If changes occur to those branches you will not have the latest commits.

There is a pattern here of being able to do things with `tags` and `branches`, which may be its own resource. I understand the conceptually, it is a `git` thing so it fits in the `git` resource. We are going to discuss this more.
