### ISSUE TITLE
Empty commits are not checked when ignore_paths is set

### ISSUE THREAD

**Issue by kirederik** [concourse/git-resource#142]
Having a git resource configured with ignore_paths disables the ability to trigger the pipeline with an empty commit.

This surprised us, because the empty commit did not contain any changes to the ignored paths. Admittedly, it also did not contain any other changes... We realise that we think of empty commits as a special case, which we sometimes use only to trigger a pipeline.

with @totherme

**Comment by jtarchie** [comment]
@kirederik, I don't think that this is something we can detect with `git` unless we had some really fancy conditional logic.

There might a different approach, which you do need to create an empty commit though. Using a time-resource that doesn't have a `trigger: true` as an input will accomplish the same thing. The versions of the time resource will increment you can trigger new builds that combined that newest version of time with the previous version of the git SHA. Happy to provide an example if needed!

I'm going to close as it is a limitation of `git`. Thanks!
