### ISSUE TITLE
Failure when cloning submodule

### ISSUE THREAD

**Issue by matbain** [concourse/git-resource#149]
In the case of a git server configured to do cloning only with ssh, the git resource fails when cloning a project containing a submodule at the time it runs _git submodule update_ command.

The issue is caused by the ssh command ran by git where it tries to connect to the server using the current username of the session. In the case of a concourse job, it is using root which makes the ssh command to fail.

Thanks,
Mathieu Bain

**Comment by vito** [comment]
Can you provide an example of a submodule URL that doesn't work? The URL itself contains the username to log in as, e.g. `git@github.com:concourse/concourse.git` logs in as the `git` user.
