### ISSUE TITLE
Allow transactional behaviour

### ISSUE THREAD

**Issue by avanier** [concourse/git-resource#150]
# Feature Request

## What challenge are you facing?

If I try to push a branch and a tag together, it's possible to push only the tag and have the branch push fail, keeping the tag pointing to an out of branch reference.

The particular use case I have is if I try to push to a GitHub protected branch, it will allow the tag to be created, but the branch push will fail, leaving a dangling tag.

## A Modest Proposal

Git allows for the use of [`--atomic`](https://git-scm.com/docs/git-push#git-push---no-atomic) which will wait for the remote repository to complete all actions successfully, or refuse all changes, essentially behaving as a transaction.

Unfortunately, this is not a behaviour configurable with `git-config`, we would need to add a parameter to the `params` block of the `out` action.

This is also not supported by all git servers.

**Comment by jtarchie** [comment]
Thanks @avanier. Appreciate the issue.

The resource actually supports different flows for `git push`, not just [branch and tags](https://github.com/concourse/git-resource/blob/e54b99675f16632bcff5db45c93aa6770ea2bf99/assets/out#L94-L96), [tags](https://github.com/concourse/git-resource/blob/e54b99675f16632bcff5db45c93aa6770ea2bf99/assets/out#L98-L100), or [notes](https://github.com/concourse/git-resource/blob/e54b99675f16632bcff5db45c93aa6770ea2bf99/assets/out#L102-L107). I'd like to see if all those workflows could be supported, rather that only one of them.

With the `--atomic` CLI, I cannot find any reference that it actually supports `--tags`. All the examples show refs being pushed, not that argument (`--tags`). I don't feel confident that this will solve your issue. Are you able to confirm it works? Or provide an example?

**Comment by ls-avanier** [comment]
I'll dig deeper... but I'm starting to get the feeling that this is potentially a smell of my pipeline having sketchy logic.

I'll test some more and provide a more concrete example.

**Comment by avanier** [comment]
I'll dig deeper... but I'm starting to get the feeling that this is potentially a smell of my pipeline having sketchy logic.

I'll test some more and provide a more concrete example.

**Comment by avanier** [comment]
I'll close this for now as I can't make time to dig into this and the project that spawned this use case got shelved. :/

I'll reopen the issue when if I trip over this use case again.
