### ISSUE TITLE
commit went missing when tracking master

### ISSUE THREAD

**Issue by michelleheh** [concourse/git-resource#152]
We have a git resource that is tracking the master resource. However, a job is specifying a particular commit by using {ref:<commit sha>}. The job has been running fine with this commit, but when we manually trigger this commit today. When we went to the resources page, we found that the resource no longer contain the commit reference. 

We used the fly cli to check the resource, and we were able to retrieve the missing commit by looking at the resource page and confirming the commit is there.

We are using concourse version v0.3.4.

Cheers,
@kkallday and @michelleheh

**Comment by vito** [comment]
Versions are never removed from Concourse (there's actually a pretty popular open issue requesting that in https://github.com/concourse/concourse/issues/145). I have a hard time believing the resource or Concourse did something wrong here. Are you sure the version wasn't just pushed to the next page or something?

**Comment by vito** [comment]
Don't have much to go on here. Reopen if you've got more info!
