### ISSUE TITLE
Resource owned by `root` user

### ISSUE THREAD

**Issue by track0x1** [concourse/git-resource#155]
I'm building an npm package (in a concourse pipeline) and the task uses a node alpine image. I have a `git-resource` that points to my source code repo and that is provided to my task as an input. When my task runs `ls -la /tmp/build`, it shows the temp folder (the repo code) as owned by `root` and group of `root`. However, node & npm need to run as a non-root user (user `node` in the node alpine image).
So now, my `node` user can't access the repo files and do its thing. How can I get the `git-resource` to provide the repo with the same user & group?

**Comment by vito** [comment]
this is probably the same as https://github.com/concourse/concourse/issues/403

for now, you'll have to `chown` them yourself and then `su node` to run the `npm` tasks
