### ISSUE TITLE
fatal error when shallow cloning repo with a path filter

### ISSUE THREAD

**Issue by bhcleek** [concourse/git-resource#158]
Given a git resource with a path filter, a repository that has more recent commits that do not satisfy the filter, and a `get` that limits the depth (`1` is the ideal value to try), the `get` will fail with a fatal error, because the `.version.ref` is not present in the shallow clone.

The problem is here: https://github.com/concourse/git-resource/blob/master/assets/in#L61-L66.

I don't have time to submit a well-tested patch now, but changing those lines to 
```
git clone --single-branch $depthflag $uri $branchflag $destination

cd $destination

git fetch origin refs/notes/*:refs/notes/*
git fetch $depthflag $ref
git checkout -q $ref
```

may well fix the problem.

**Comment by bhcleek** [comment]
In addition to the issue of a git resource filter on the path, I realized that this same behavior can manifest itself due to a race condition between the time a new version is detected and the time the job runs; in the interim, another commit could have been pushed, causing the same fatal error.

**Comment by timrchavez** [comment]
@bhcleek Assuming I have the test correct, I do not think your change will work. I'm getting ```running it_can_shallow_clone_ref_with_new_commits...
  Switched to a new branch 'bogus'
  Switched to branch 'master'
  Cloning into '/tmp/git-tests.dlHJcd/git-tests.JFhcGp/destination'...
  error: Server does not allow request for unadvertised object 57b3b83c0199e8d73a1d1921785f2f73b0eb5ddf
The command '/bin/sh -c /tests/all.sh' returned a non-zero code: 1
```

The test is adding a couple commits but setting `version.ref` to the first commit.

**Comment by timrchavez** [comment]
Updated to fetch enough depth to ensure `git checkout -q $ref` succeeds.

**Comment by timrchavez** [comment]
Wondering if there's any news on this being accepted (or rejected)?

**Comment by timrchavez** [comment]
Totally getting back to this :)
