### ISSUE TITLE
Git shallow clone

### ISSUE THREAD

**Issue by elgohr** [concourse/git-resource#164]
As seen in https://github.com/concourse/git-resource/blob/93e292dca4258ec9893efca6ee84f57f7f5f2a3e/test/get.sh#L156 the git resource honors the `--depth` flag, if present.
Nevertheless, by default, the whole repository is cloned.
Refering to https://www.perforce.com/blog/git-beyond-basics-using-shallow-clones I would suggest to change the default behaviour to be `--depth 1`. In this way people had to increase the size manually or set it to -1 to get the full repository. 

Why?
- Decrease traffic/load for loading from git
- By default people don't load a git repository and have a job to travel back in time

I would create a pull request, if we come to the point that this would make sense.

**Comment by vito** [comment]
Sorry, but we won't be making it the default. Having it default to any depth would break a few common use cases. We had to add a warning to the `depth` param and people are, as predicted, running into problems when using it.

Commit history is useful for a few common cases:

1. When a sha is progressing through the pipeline, at some point it may no longer be the latest (if an engineer pushes more code while it's partway through). There's no way with `git` to clone starting at a commit, so we'd need to clone deep enough to get the commit, which there's no clean way to do.
1. When making a commit to the repo and pushing, merging, or doing anything really, this can't always be done from a shallow clone.

I get that it can be quite slow to fetch the full depth, but it's the safest default, and there's a knob if you want to try optimizing it. There may be other options to explore that could make the cloning quicker, i.e. a local cache mechanism for resources.
