### ISSUE TITLE
Use API Access Token

### ISSUE THREAD

**Issue by quasiben** [concourse/git-resource#169]
Is it possible to use API access token to pull/push a repo? This issue was closed before anyone responded: https://github.com/concourse/git-resource/issues/6

**Comment by vito** [comment]
No, it's not possible; this is a general `git` resource, there's no such thing as API access tokens for just `git` (that's GitHub, BitBucket, etc. -specific).

GitHub allows you to configure deploy keys on the repo, so you could do that if you want revokable anonymous, optionally read-only, access.

**Comment by quasiben** [comment]
Ah, thanks.  I'll close now
