### ISSUE TITLE
Retriggering on a force push

### ISSUE THREAD

**Issue by olivercf** [concourse/git-resource#174]
I have a git resource tracking a branch that feeds into a build job, and then a deploy job. I want to be able to deploy arbitrary branches, e.g. a feature branch, then production, then a different feature branch, then back to the first feature branch, etc. I have a branch for the environment that I move around by force-pushing (i.e. `git branch -f branch-name destination && git push -f origin branch-name`) which works and triggers the build, but only for commits that haven't been built before. If I want to redeploy the original feature branch, there is no way I can do it without editing the pipeline or creating empty commits. What should I do in this scenario?

**Comment by emcniece** [comment]
Can't remember where I saw it, but somebody wrote about how they were using empty commits to re-trigger. Dirty, but it works.

**Comment by xulsitatirev** [comment]
Hmm; pretty nice problem, I have just met. We do use `gitflow`.
For `gitflow` it is forbidden to `push` to `develop` and `master` branches, but I can imagine workflow, where `feature/x` is handled by `concourse` as `CI` system and I would say `force-push` might be allowed there.

**Comment by vito** [comment]
I'm about 99% sure this all be resolved with a combination of https://github.com/concourse/concourse/issues/1707 (which will enable support for feature branches) and concourse/rfcs#1 (which will improve handling of force-pushes). 🙂 I'm gonna close it for now to keep our issues tidy but feel free to keep track of those two epics here: https://github.com/concourse/concourse/projects
