### ISSUE TITLE
Pass path to SSH key instead of pasting it into yaml

### ISSUE THREAD

**Issue by Raketemensch** [concourse/git-resource#187]
I would prefer not to have to commit private keys in plaintext files in github.

Having the ability to specify a path to a key would be a simple way to work around this dangerous security situation. Something like:

  source:
    uri: git@github.com:concourse/concourse-docker.git
    branch: master
    key: /keys/id_rsa

**Comment by 0815fox** [comment]
Also it would make it easier to use a template of a pipeline in multiple projects with different keys.

**Comment by vasilgerman** [comment]
Also please!

**Comment by vito** [comment]
There is no filesystem from which to read the keys.

This should be solved by way of [credential management](https://concourse-ci.org/creds.html).
