### ISSUE TITLE
Checkout non-detatched mode

### ISSUE THREAD

**Issue by Jarlotee** [concourse/git-resource#198]
It looks like currently git always checks out master in detached mode.

But I need to reference what branch has been selected for some automation scripts

Is there parameter to toggle the detached behavior?

**Comment by Finkregh** [comment]
is this under consideration? This has been open for a year now and did not get any feedback :(

**Comment by vito** [comment]
Seems like an easy feature to PR. The resource could write to `.git/branch` just like it writes to `.git/ref` already.
