### ISSUE TITLE
Poll in a more lightweight fashion so peoples' self-hosted Git servers stop exploding

### ISSUE THREAD

**Issue by vito** [concourse/git-resource#199]
Instead of running `git fetch` we could maybe do a lighter check to see if we're already up-to-date with the remote (perhaps `git ls-remote`), and *then* do a `git fetch` only if the remote is different.

We should verify that this actually helps before implementing it.

**Comment by vectorstorm** [comment]
For what it's worth, I've just tested this idea on two different live Concourse installations which each happen to use self-hosted Git servers.  One is a very fast cloud server with an SSD and with a large git repo self-hosted on a separate cloud server.  The other is a much slower machine with a conventional hard disk talking to slow version control software hosted on the same slow machine, and a much smaller git repo.  Both showed similar results.

All these tests were done when there were no changes to be fetched.

## Testing procedure:

### TIME:
`time git ls-remote --heads origin master` vs `time git fetch origin master`

I ran each command multiple times within the git resource container and took the average result. (variances were very small)

**Faster machine with large git repo and fast version control server:**
- `git ls-remote origin master`:  0.26s real time
- `git fetch origin master`:  0.28s real time

**Slower machine with smaller git repo and slow version control server:**
- `git ls-remote origin master`: 1.2s real time
- `git fetch origin master`: 1.4s real time

The time difference between `ls-remote` and `fetch` were small, but consistent.  Fetch was always slower than ls-remote by a fraction of a second.

### BANDWIDTH:
`git ls-remote origin master` vs `git fetch origin master`

I tested bandwidth usage outside the git resource containers, using `nethogs` in absolute display mode (I assume the network usage will be the same regardless of where it's coming from, so I didn't bother to rebuild a git-resource container that had a copy of nethogs in it).

**large git repo:**
- `git ls-remote origin master`:  5.9KB up, 31.1KB down
- `git fetch origin master`:  5.5KB up, 31.0KB down

**smaller git repo:**
- `git ls-remote origin master`:  4.8KB up, 8.4KB down
- `git fetch origin master`:  4.7KB up, 8.4KB down

I'm puzzled by this result, but on average, `ls-remote` seemed to use very slightly *more* bandwidth than `fetch`, when there were no changes to be fetched.  The difference is a fraction of a kilobyte;  perhaps it's the commit sha that 'fetch' doesn't have to transfer when there are no new changes, but ls-remote still needs to send?

In any case.. based on these tests, I'm not convinced that `git ls-remote` is any more "lightweight" than `git fetch` either in terms of time taken or in terms of network usage in the case where there are no changes to be fetched;  presumably git is already doing this sort of test itself, inside the fetch?

**Comment by vito** [comment]
@vectorstorm Very interesting, thanks for investigating. :+1: It does seem like it would make sense for `git fetch` to do a lighter check on its own, if that is indeed the case.

I'm just going to close this then. It sounds like a nice idea but I think we'd need a new lead.

**Comment by simonjohansson** [comment]
We have some teams with large repos (~2GB)

In some cases some of these repos contain lots of subapps, yay mono-repos.

For example `repo` contains 50 apps. That means we have 50 pipelines with 50 git resources with unique `watched_paths` thus 50 check containers that each have a copy of a 2 gig repo. Not all of these sub-apps are actively developed on a weekly basis. Say 20 of they are ephemeral services. That means that we are cloning the full repo 480 times a day (~1TB transfer) for pipelines where nothing has changed. Seems a bit wasteful when `ls-remote` would suffice to figure out that nothing has changed :).

```
$ time git ls-remote git@github.com:springernature/bigBadRepo.git
 0.03s user 0.03s system 3% cpu 1.821 total
```

https://github.com/concourse/concourse/issues/2923

**Comment by vectorstorm** [comment]
All the tests I did in my comment above (comparing fetch to ls-remote) were comparing in the instance where there were no changes to fetch.  It seems likely that ls-remote would be vastly cheaper in terms of bandwidth than actually fetching a full clone into the check container;  I hadn’t realised we were doing that every hour!

In theory, we *ought* to be able to get branch head commit shas and tags that way, far cheaper than doing a fresh clone every hour, especially for large repos (I’m maintaining one which is currently sitting at about 30 gigabytes for a single project!).

Only bit that has me stumped is a way to get the commit messages so we can test for ‘[ci-skip]’ without having a local clone of the repo.
