### ISSUE TITLE
`paths` option broken for merge commits

### ISSUE THREAD

**Issue by thewoolleyman** [concourse/git-resource#21]
If you have a `paths` option, then the `check` script will fail to trigger for merge commits even if the commits which they merged in contained changes to files which are included in `paths`.

Presumably this is because of the shallow clone, so there's NO files included in the merge commit.

**Comment by xoebus** [comment]
Merge commits never change any files according to `git` (unless there were conflicts). The way we worked around this in the past is to [look back in the history](https://github.com/concourse/git-resource/commit/c8c408dc264ad79741a05b242238c4d9771cdbd7) to calculate the files that were touched. If that information isn't there (because a shallow clone was used) then I'm not sure there's much we can do.

Unfortunately this is probably a *WONTFIX* unless there is somewhere else we can get the information we need.

**Comment by thewoolleyman** [comment]
OK, so, if the ref span looked at is greater than your clone depth, you could miss check triggers with `path` specified.

Does that characterize the problem correctly?

If so, there's not an easy solution, but we could at least give some warning, or fail if this could be detected or predicted (e.g. if there's merge commits in the range that was looked at in the git log grep, or especially if there's ONLY merge commits).

Thoughts?

**Comment by xoebus** [comment]
Yeah, a warning is a good idea.

The only place we could show this warning at the moment is to have the resource show up as failing and have the error be an explanation of the problem. Does that sound OK?

**Comment by thewoolleyman** [comment]
Yes, that's the only option with resources, right?  Are there other options planned for the future?

**Comment by vito** [comment]
I'm leaning towards just killing the `depth` flag now that we've implemented caching. It's going to be a constant source of pain.

**Comment by thewoolleyman** [comment]
@vito Strong -1 on killing it, for huge repos its a great optimization on the first clone.  And, given our dynamic pipeline generation approach, we recreate new pipelines and git resources all the time, and we have a huge repo.  So it would be a big performance/time hit to us to lose the depth optimization option.

**Comment by thewoolleyman** [comment]
@vito And FWIW, once we realized the root problem (your depth has to ensure that you never get all merge commits), we just set all our depths to 50 and things were great.

So, this is really an edge case.  I'm fine closing it as wontfix, but please don't kill the depth option.

**Comment by xoebus** [comment]
We won't be removing the `--depth` flag but closing this as `WONTFIX`.
