### ISSUE TITLE
Tag filter not working

### ISSUE THREAD

**Issue by AndrewMorsillo** [concourse/git-resource#211]
Perhaps I'm doing something silly, but it seems that the tag filter isn't working for me in some cases.

If I set ```tag_filter: v*``` and tag "v0.1.3" things work. If I set ```tag_filter: prod*``` on one pipeline and ```tag_filter: staging*``` on the other pipeline to separate my staging and production tags my builds never trigger when I make a tag like "prod0.1.3" or "staging0.1.3".

Am I missing something obvious here or are there some cases where the tag filter won't work?

**Comment by lbathina** [comment]
I am facing the same issue. I have tag filter to be  tag_filter: "[0-9]*". This was working (auto triggering) on older version of concourse. But on new one it doesn't

**Comment by talset** [comment]
@AndrewMorsillo did you configured a branch on your git resource ?
Is your tag on prod and staging are comming from a branch ?

**Comment by AndrewMorsillo** [comment]
I upgraded to the latest version of concourse and it is working correctly there
