### ISSUE TITLE
[Question] Necessity for tag_filters to trigger exclusively on tags

### ISSUE THREAD

**Issue by aledegano** [concourse/git-resource#213]
Hello,
I have a question: is there a fundamental reason (that probably I'm missing) for NOT triggering ALSO on commits when the option `tag_filters` is set?

The reason I'm asking is the following: given that a git-resource where `tag_filters` is set will not trigger on normal commits that forces me to have a duplicate resource or task or job or pipeline.

In my use case I'd like a pipeline that behave exactly the same whether it's building upon detecting a new commit or upon detecting a tag (that might also be assigned to an older commit).  After the pipeline completes I'll deploy if the trigger was coming from a tag, but that's a different story.

IF there's no fundamental reason to preserve the current behavior do you have any idea on how you would configure the resource to trigger both on commits and tags? If so I might be able to propose a PR to achieve my desired behavior.

Thanks!

**Comment by dbaumgarten** [comment]
@aledegano Have you ever found a solution for this?

I am having the exact same question.

**Comment by taylorsilva** [comment]
The "fundamental" reason is the "external state" that the resource represents in those two scenarios:

- Commits with a tag
- Commits without a tag

They're two different things, so Concourse wants you representing them as two distinct resources.

As for the specific problem OP had, my first thought is to try using a gated pipeline pattern. You could:

1. Have two instances of the git resource, with and without commit tags. Job-1 `get`'s both resources, but only trigger on the "all commits" resource. Second, deploy job, only triggers on "tagged commits".
2. Use a single instance of the git resource and trigger on all commits in job-1. You could have a "gate" job after job-1 that fails if the passed commit does not contain the tag and avoids passing along non-tagged commits.
