### ISSUE TITLE
What is refs/notes?

### ISSUE THREAD

**Issue by DanielJonesEB** [concourse/git-resource#235]
In debugging a problem pushing with a rebase (where the rebase seems to be happening against the wrong remote), I discovered this: https://github.com/concourse/git-resource/blob/master/assets/out#L180

I've never seen nor heard of "refs/notes/*" before. The [Git docs for refspec](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec) don't mention notes anywhere. There's [`git notes`](https://git-scm.com/docs/git-notes), but this seems entirely unrelated to what one might want to do when rebasing before a push in CI.

Why does this line specify the refspec argument? What would happen if it wasn't in there?

**Comment by vito** [comment]
A cursory `git blame` reveals it was added as part of https://github.com/concourse/git-resource/pull/103

**Comment by DanielJonesEB** [comment]
Ta. Apologies for not doing the bear minimum to answer my own question. I'd like to blame being on a train with crappy wifi, but it's more that I'm lazy.

**Comment by vito** [comment]
Haha no worries!
