### ISSUE TITLE
Path and Branch source options for git resource do not work together?

### ISSUE THREAD

**Issue by Ianwww** [concourse/git-resource#236]
Path and Branch source options for git resource are not working together.  Using the following configuration, concourse continues to pull from master. 

- name: app_source_code
  type: git
  source:
    uri: ((git_url))
    branch: com-44
    private_key: ((git_private_key))
        paths:
           - coms/*

**Comment by vito** [comment]
I'm pretty sure these params work, we use them in our own pipeline and there's no real reason they'd interact strangely.

There's not a whole lot to go on here; those aren't really steps to reproduce since it doesn't have the repo URL.

Try using `coms/**/*` instead?

**Comment by Ianwww** [comment]
correct, it's not a bug. I had an incorrect glob pattern, changed coms/* to coms/** and also the files I was modifying where in another path, so I added that to the list of paths. thanks
