### ISSUE TITLE
switch to using ubuntu for base image

### ISSUE THREAD

**Issue by chenbh** [concourse/git-resource#240]
## Why
tldr: Patching ubuntu images is faster and more reliable than alpine

## Impacts
* The resource image will be larger (272mb -> 383mb)

**Comment by larssb** [comment]
Hi @chenbh,

Out of curiosity I would like to know/read info on `alpine` being less reliable in regards to patching and day-to-day operation. Do you have some URI's or other types of documentation on this?

I would highly appreciate it.

Thank you and have a good 1.

**Comment by chenbh** [comment]
Hey @larssb there's more context in the parent issue https://github.com/concourse/concourse/issues/3266#issuecomment-463227274

One more thing to note is that we are currently using `alpine:edge` which can be a bit unstable due to its nature. 

If we are to switch to Alpine 3.9 (latest stable currently) it still only has a support window of 2 years till 2021 (https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases).

On the other hand Ubuntu 18.04 has a LTS till 2023 (https://wiki.ubuntu.com/Releases)
