### ISSUE TITLE
Submodule update uses name instead of path for submodules: all

### ISSUE THREAD

**Issue by DigitalCoffee** [concourse/git-resource#246]
Hi!

I'm using Concourse to build/deploy my applications. I upgraded my Concourse BOSH deployment from v4.2.3 to v5.0.0 and found an issue when my pipeline pulls my project repo.

### Issue
Repositories containing submodules with names that are not the same as their path cannot be retrieved through this resource. The submodule update fails because the name is used rather than the path.

Here's a quick way to reproduce the issue:

Create a new git repository and add a submodule with the following command:
`git submodule add --name "testmodule" <submodule_repository_url> "path/to/submodule"`

This should create the following .gitmodules:
```
[submodule "testmodule"]
	path = path/to/submodule
	url = <submodule_repository_url>
```
Commit & push these changes to a remote repo. Create a pipeline that uses this resource to pull from the repo with default `get` params (or `submodules: all`).

The `get` step fails in Concourse v5.0.0 with output:
```
Submodule 'testmodule' (<submodule_repository_url>) registered for path 'path/to/submodule'
error: pathspec 'testmodule' did not match any file(s) known to git
```

It looks to me that the issue comes from [this](https://github.com/concourse/git-resource/blob/62f1204144b2e7c37a35bae1b322bf82491b8745/assets/in#L137) method of determining the submodules, which occurs if `submodules: all` param is used for the `get` step. Using `git config` lists the submodule names, where the `git submodule update` [further down](https://github.com/concourse/git-resource/blob/62f1204144b2e7c37a35bae1b322bf82491b8745/assets/in#L156) expects paths to the submodules.

I think using `git submodule` and extracting the path from the output should work.

A quick fix for anyone running into this issue is to simply run a `git mv` or try renaming the submodule so that their names and paths match.

**Comment by cunnie** [comment]
We're seeing the same problem with the [CF Networking Release](https://github.com/cloudfoundry/cf-networking-release):
```
+ git submodule update --no-fetch --recursive src/github.com/cloudfoundry/cli
error: pathspec 'src/github.com/cloudfoundry/cli' did not match any file(s) known to git
```
Here's the input we're passing in:
```json
{
  "source": {
    "uri": "https://github.com/cloudfoundry/cf-networking-release",
    "branch": "master"
  },
  "version": { "ref": "427a60f213993e884636bd234596ce557732b5e4" }
}
```
Here's the stanza from [`.gitmodules`](https://github.com/cloudfoundry/cf-networking-release/blob/507f010f43c57254c1de46e4f0cbfe25bfbc15a7/.gitmodules#L52-L54):
```
[submodule "src/github.com/cloudfoundry/cli"]
	path = src/code.cloudfoundry.org/cli
	url = https://github.com/cloudfoundry/cli
```

**Comment by vito** [comment]
Thanks for the report, it does look like a regression.

**Comment by jzingler** [comment]
I ran into a similar issue and added the `git submodule update --init --recursive` command to execute from my pipelines build script. Note: Make sure you're in the source code directory when you run the command.
