### ISSUE TITLE
Feature Request: Add --no-tags parameter for git clone

### ISSUE THREAD

**Issue by lindenquan** [concourse/git-resource#249]
when concourse git resource tries to "git clone --single-branch", it also fetches tag objects which are not needed at all. 
It also cased git clone failed with the following message
fatal: did not receive expected object 6b00a8c61ed379d5f925a72c1987c9c52129d364
fatal: index-pack failed

Actually object 6b00a8c61ed379d5f925a72c1987c9c52129d364 is an tag object.
I have set the depth to 1, but git clone still shows the same error.

Thanks very much!

**Comment by talset** [comment]
This feature could be linked to https://github.com/concourse/git-resource/issues/312#issuecomment-610829051

Ideally a param to enable or disable tags fetch when not using `tag_filter`.

I might be able to work on it next week

**Comment by talset** [comment]
I had a look on `--no-tags`. If we decide to use it as "default" it will reduce the metadata information about the commit (https://github.com/concourse/git-resource/blob/master/test/get.sh#L132)

Should we do it anyway ? Or should we keep the same default (without --tag/notag) and have a param to fetch or not tags ?
