### ISSUE TITLE
Get rid of `git lfs`

### ISSUE THREAD

**Issue by YoussB** [concourse/git-resource#250]
running a fly execute locally gave me this message: 
```
WARNING: 'git lfs checkout' is deprecated and will be removed in v3.0.0.
'git checkout' has been updated in upstream Git to have comparable speeds
to 'git lfs checkout'.
```
might be time to get rid of `git lfs` and use plain `git checkout`

🤔

**Comment by vito** [comment]
This is already fixed by https://github.com/concourse/git-resource/pull/248
