### ISSUE TITLE
Missing metadata for old commits

### ISSUE THREAD

**Issue by fiftin** [concourse/git-resource#258]
Most of old commits (not all) has no metadata:

![image](https://user-images.githubusercontent.com/914224/56645635-7fb25800-6697-11e9-8d08-c0f21cc02ba9.png)

Last commit always has metadata.

Concourse v5.0.1

**Comment by fiftin** [comment]
What interesting - this metadata not missing in task log which use git-resource.

**Comment by vito** [comment]
This is expected behavior - currently metadata only appears when a `get` or a `put` runs for the corresponding version. This will be fixed by the new resource interface (concourse/rfcs#24).
