### ISSUE TITLE
checkout tag

### ISSUE THREAD

**Issue by demchris** [concourse/git-resource#264]
I would like to be able to track change not on branch but tag. I have to track change on git repository not belong our team and they don't work with branch but with tag.

Instead of doing a git checkout -b <branch>, the resource would have to do a simple git checkout <tag>.

Thank you,

Christian

**Comment by vito** [comment]
I'm not sure what you mean... The resource doesn't do a `git checkout -b`. What behavior change are you asking for? The resource also supports `tag_filter` for tracking tags independently of branches.

**Comment by demchris** [comment]
Hi Vito, sorry for delay.

Thank you for quick answer. I tried yesterday but got stocked at : Discovering new version. I retried today and everything works as expected. Probably for another issue in my pipeline.

Work well with tag_filter
