### ISSUE TITLE
Ability to specify maximum number of retries?

### ISSUE THREAD

**Issue by EduardoAC** [concourse/git-resource#265]
Recently, I have this problem during rebase that it's causing an infinite loop 

Is there a way to specify a "max retry" count? Or some other way to have the job fail after a certain amount of time?

![Screenshot 2019-07-11 at 10 15 45](https://user-images.githubusercontent.com/2104706/61043414-1c9aac80-a3ce-11e9-9549-a9e6b792498c.png)

Thank you for your time, I appreciate it.

**Comment by ukabu** [comment]
We have the same issue. It really should fail after a few retries (there should be a default max number of retries).

**Comment by spion** [comment]
After submitting a PR for this, I realized concourse already has a [`timeout` option](https://concourse-ci.org/timeout-step.html) which will stop the step after some time. In the absence of retries I think that should do the trick.

**Comment by taylorsilva** [comment]
Workaround provided by @spion to use the `timeout` step modifier. Closing this issue since it's not worth fixing since `timeout` will get you the same behaviour, albeit slightly less robust.

**Comment by EduardoAC** [comment]
@taylorsilva It makes sense; thanks for letting me know
