### ISSUE TITLE
Changing the resource configuration has no effect

### ISSUE THREAD

**Issue by friegger** [concourse/git-resource#27]
Resource caching [1] prevents the git_resource from recognizing changes to the resource configuration. e.g. branch, uri

[1] https://github.com/concourse/git-resource/blob/master/assets/check#L29

**Comment by vito** [comment]
Looks like this regressed, probably with 0.71. Not a bug with the git resource; we shouldn't be reusing containers at all if the source changes. Dragging this in; should be fixed soon.
