### ISSUE TITLE
recursive submodules and triggering

### ISSUE THREAD

**Issue by weberstephanhd** [concourse/git-resource#29]
Hi,

I just wonder about the following scenario:

````
GitRepoA*
+--- SubmoduleAA*
:    +--- SubmoduleAAA
     |    +--- fileAAAA
     |    +--- fileAAAB
     +--- SubmoduleAAB*
     :    :
````

SubSubModule AAB has changed, therefore SubmoduleAA and GitRepoA were changed, too (new submodule commits). SubmoduleAAA has no changes.

If GitRepoA is my source-uri, how do I express that I get triggered only if I had a change on fileAAAB? Just setting "paths: [SubmoduleAA/SubmoduleAAA/fileAAAB]" ???

Best regards, Stephan

**Comment by vito** [comment]
This would be pretty hard to add, and I'm not sure it's worth it to be honest. `paths` and `ignore_paths` should only apply to the top level; it's easier to understand how they work when knowing they're just arguments passed to `git log`.

**Comment by vito** [comment]
Closing this since we're unlikely to fix it and the issue's been inactive.
