### ISSUE TITLE
wrong last commit reported with list_command | git rev-list --stdin

### ISSUE THREAD

**Issue by talset** [concourse/git-resource#293]
On a customer git it seems they had a weird commit with year 2106 instead of 2016 :

```
commit d1f0d5f316ffd6a7ba9e03198e4aae55b3d2efb1
Date:   Tue Dec 10 12:34:33 2019 +0100

...

commit 06a8e882889e6e164018271f000330d4c23004bd
Date:   Sun Feb 7 06:29:14 2106 -9039932

commit 86ddfd204e0f7b07492e220c9da1dfd0b422def2
Date:   Wed Jun 1 11:41:20 2016 +0200
```

Since https://github.com/concourse/git-resource/commit/c7ce409128070a3d4b7abd2643565851a1a02dc9 / https://github.com/concourse/git-resource/pull/271

`06a8e882889e6e164018271f000330d4c23004bd` is detected as the latest commit each time.

In this case the cmd is
```
git rev-list --all --first-parent   | git rev-list --stdin --grep="\[ci\sskip\]" --grep="\[skip\sci\]" --invert-grep --first-parent --no-walk| git rev-list --stdin -1
```

What is the purpose of this ?
Should it be reverted ? Or changed by `list_command+="| git rev-list --stdin --date-order -1"` ? Or simply `list_command+="| head -n1"` ?

**Comment by talset** [comment]
What do you think @CliffHoogervorst ?

**Comment by talset** [comment]
@CliffHoogervorst did you had time to have a look ?

**Comment by talset** [comment]
@pivotal-jamie-klassen any idea on this ?

**Comment by RichardBradley** [comment]
I have a similar issue: due to a rebase, I have one commit on my branch with a commit date that is newer than the head of the branch (in my case it's a few minutes newer, not 100 years!).

The Concourse git-resource now picks that commit as the "latest" on the branch, even if I explicitly name the branch on the resource:

```
  - name: "myapp-src"
    type: git
    icon: github-circle
    source:
      uri: "git@github.com:me/myapp.git"
      private_key: ((github-private-key))
      branch: master
```

How can I get Concourse git-resource to correctly track a branch, rather than incorrectly sorting commits by commit date?

**Comment by talset** [comment]
@CliffHoogervorst could you come back to us ? Maybe @vito have some ideas ?

I could do a PR to change `list_command` but I would prefer to have @CliffHoogervorst feedback before reverting or changing anything.

The current workaround is to "disable" the "faulty" commit on concourse resource.

**Comment by simonjohansson** [comment]
We just saw the same behaviour as @RichardBradley described. Rebase involved

```
* commit order in Concourse
commit2 - Wed Mar 18 09:20:23 2020 +0000
commit4 - Wed Mar 18 09:09:00 2020 +0000
commit3 - Wed Mar 18 08:51:34 2020 +0000
commit1 - Wed Mar 18 08:47:43 2020 +0000

* commit order in git
commit4 - Wed Mar 18 09:09:00 2020 +0000
commit3 - Wed Mar 18 08:51:34 2020 +0000
commit2 - Wed Mar 18 09:20:23 2020 +0000
commit1 - Wed Mar 18 08:47:43 2020 +0000
```

**Comment by talset** [comment]
PR https://github.com/concourse/git-resource/pull/310 have been created with the `head` cmd fix.

**Comment by talset** [comment]
@RichardBradley @simonjohansson Are you able to reproduce the issue ?
If yes do you have the git command to have this behaviors ?
