### ISSUE TITLE
Deepen shallow clone does not deep correctly for depth > 1

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/git-resource#315]
https://github.com/concourse/git-resource/blob/f0d57ba2b7d43eb37dd001e14fe8bbb874b9a49a/assets/deepen_shallow_clone_until_ref_is_found_then_check_out#L47

I've encountered a case where the git-resource is not correctly deepening a clone. I've specified `depth: 2` and expect to get `version.ref` + its previous commit fetched. However, in the following edge-case the previous commit is not fetched correctly.

The script retries fetching with ever larger `--depth` until the desired ref is found. However, this depth is always relative to the latest HEAD of the remote branch. This may move forward while the retry loop is in progress. 

The correct behavior would be to use `git fetch --deepen` instead, see https://git-scm.com/docs/git-fetch#_options

**Comment by YoussB** [comment]
Hey @JohannesRudolph 
Thanks for the issue and the PR. we'll get to the PR soon,

**Comment by scarytom** [comment]
We have just upgraded our concourse instance, and we are now getting this error

```
fatal: Server does not support --deepen
fatal: The remote end hung up unexpectedly
```

It would appear that bitbucket (where our code is hosted) does not yet support `git fetch --deepen`.  Was this bugfix considered as a breaking change when it was applied?  I suspect quite a few users of concourse might get bitten by this.

**Comment by JohannesRudolph** [comment]
Sorry to hear you ran into this issue. I did actually run into the same and left that as a comment on my PR at https://github.com/concourse/git-resource/pull/316#issuecomment-614130690

I think the situation is a bit unfortunate with bitbucket being that much behind on git versions (~4 years as of writing). That means you're either stuck with an old version of git resource (you can always pin your pipeline to use an old version) with a broken deepen algorithm. Or you're stuck with finding a new git server...

**Comment by scarytom** [comment]
Yeah, sucks to be on bitbucket.

**Comment by scarytom** [comment]
@JohannesRudolph do you know how to pin the version of the git resource type?  Given this is a "core" resource type, it doesn't have a resource_type entry in the pipleline, which is where I would normally pin.
