### ISSUE TITLE
Make `branch` parameter optional and default to 'master'

### ISSUE THREAD

**Issue by seadowg** [concourse/git-resource#34]
I think it would be a nice tweak to reduce mistakes when people first start and also kills a line of .yml in most people's pipelines.

**Comment by tomwhoiscontrary** [comment]
As long as you're only getting from a git resource, the branch parameter is actually already optional. We have a load of git resources which don't declare branches, and they work fine.

It does seem to be necessary if we want to put to the resource, though.

**Comment by seadowg** [comment]
Ah awesome. Maybe this changed from the version I was using (around 0.7x).
I'll give it a try.

**Comment by vito** [comment]
Closing; it defaults to whatever the default branch is, though it's necessary for `out` as being explicit seems important there.

**Comment by nebhale** [comment]
@vito There's probably some improvement to be done to the documentation around this.  The subtlety about required for `out`, but not for `in` doesn't show up in the `README`.
