### ISSUE TITLE
path: dir/**/* not triggering

### ISSUE THREAD

**Issue by bodymindarts** [concourse/git-resource#36]
We have a pipeline that is not getting triggered on a change to `dir/file.md` when defining the glob `dir/**/*`. When using `dir/*` it works.

Locally the commands `git log --format='%H' --reverse $ref..HEAD -- dir/**/*` and `git log --format='%H' --reverse $ref..HEAD -- dir/*` produce the same output.

**Comment by vito** [comment]
The glob `foo/**/*` means "files in directories living in `foo`". Sounds like this is working as intended.

```sh
~ $ mkdir foo
~ $ cd foo
~/foo $ touch toplevel-file
~/foo $ mkdir subdir-1
~/foo $ mkdir subdir-2
~/foo $ touch subdir-1/nested-1
~/foo $ touch subdir-2/nested-2
~/foo $ cd ..
~ $ echo foo/**/*
foo/subdir-1/nested-1 foo/subdir-2/nested-2
~ $ echo foo/*
foo/subdir-1 foo/subdir-2 foo/toplevel-file
~ $
```

You can also just specify `dir`.

**Comment by DimitarVoynov** [comment]
Hi @vito, 

following the test from your last comment I tried:
`~ $ echo foo/{**,.}/*`
This correctly resulted in:
`foo/subdir-1/nested-1 foo/subdir-2/nested-2 foo/./subdir-1 foo/./subdir-2 foo/./toplevel-file`
i.e. all sub-dirs, top level files and files in sub-dirs are matched. 

So far so good. The same does not work though when I have it in a pipeline: 
`...
paths:
    - foo/{**,.}/*
...`
By "not work" I mean - changes in the toplevel-file are not detected by the git resource!?

Can you please clarify and check. 

Thanks!
Dimitar
