### ISSUE TITLE
`annotate` param should be relative to the container, not the repo

### ISSUE THREAD

**Issue by vectorstorm** [concourse/git-resource#42]
It's worth noting that the filename for the 'tag:' parameter needs to be expressed relative to the base of the container (e.g.: `version/number`), whereas the filename for the 'annotate:' parameter needs to be expressed relative to the base of the git repository (e.g.: `../version/number`)

Not too difficult to figure that out by reading the source, but it's a surprising piece of information that should probably be called out explicitly in the documentation.

**Comment by vito** [comment]
Oh, that should probably be fixed actually, don't think it was meant to work that way (all file parameters should probably be relative to the base).

/cc @Jonty

**Comment by Jonty** [comment]
Oh that's absolutely a mistake, I have no idea how we missed that during testing! Apologies.

**Comment by vito** [comment]
@Jonty Was this fixed?

**Comment by Jonty** [comment]
@vito No, this slipped off our radar. I'll get it looked at next week if our schedule allows.

**Comment by vito** [comment]
fixed by https://github.com/concourse/git-resource/pull/168
