### ISSUE TITLE
Merge commits not being detected

### ISSUE THREAD

**Issue by nebhale** [concourse/git-resource#43]
At some point recently (I think it's recent), merge commits have stopped being detected.  For example, given a repository's commit log:

![screen shot 2016-04-11 at 15 04 33](https://cloud.githubusercontent.com/assets/60754/14443892/f6ea4f1e-fff6-11e5-928e-4fb3006f3dde.png)

and the resource history:

![screen shot 2016-04-11 at 15 04 02](https://cloud.githubusercontent.com/assets/60754/14443896/04bcf9d4-fff7-11e5-9120-c2142f47b5ba.png)

Note that the following commits aren't listed:

* `76730de`
* `be5d390`
* `52d3397`
* `c135c4d`

The common thread is that these are all merge commits.  We use merge commits to delineate units of work, but the thing that has flagged this for us is that we use them to trigger Pivotal Tracker transitions.

![screen shot 2016-04-11 at 15 08 54](https://cloud.githubusercontent.com/assets/60754/14443952/59d2d84e-fff7-11e5-8b9f-cf6cfada3e46.png)

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by tyyko** [comment]
We are facing the same issue and this breaks the possibility to simply push changes back to the repository for us.

**Comment by vito** [comment]
This must be a bit more complicated than simply not detecting them - I've seen them detected just fine, in fact they were causing problems in #39.

I've just pushed a related commit - maybe what you were seeing is actually a manifestation of the same issue?:

https://github.com/concourse/git-resource/commit/7cd2be1f937844325458ee0644920605b6eae091

**Comment by vito** [comment]
One other thing to check for: are you using `paths:`?

**Comment by vito** [comment]
Added an explicit test showing merge behavior with regard to `paths`, if that indeed was the case. Merging in general seems to behave much more reasonably now.

**Comment by nebhale** [comment]
@vito This appears to work as I'd expect now.  Thanks for the effort.

**Comment by siredmar** [comment]
I am using V5,7,0 and git-resource does not seem to detect a git rebase... Does anyone have similar problems?
