### ISSUE TITLE
Support ssh private key which set a passphrase

### ISSUE THREAD

**Issue by takuan-osho** [concourse/git-resource#49]
I have read [Concourse CI documentation](http://concourse.ci/introduction.html) and couldn't find the git resource type settings in case of ssh private key which set a passphrase.

Could you support ssh private key which set a passphrase? Or is Concourse CI team responsible for this problem?

**Comment by keymon** [comment]
Correct me if I am wrong, but if you want to use a key with a passphrase, you must pass define the passphrase in the resource, which it is practically the same than not using passphrase. 

Or do you have other solution in mind, like use some credential store in concourse?

Anyway, you can try generating creating a version of the ssh key without a passphrase:

```
cp id_rsa id_rsa_no_passphrase
old_passphrase=secret123

ssh-keygen -p -P $old_passphrase -N '' -f id_rsa_no_passphrase
```

**Comment by takuan-osho** [comment]
Thank you for your response, @keymon .

As you said, I noticed that it is not a requirement for me to use an ssh key with a passphrase after I submitted this issue. 

So, I'll close this issue. (If I can't this issue, please close it.)
I appreciate your help.

Thanks!
