### ISSUE TITLE
in parameter - specify a tag based on a file

### ISSUE THREAD

**Issue by drnic** [concourse/git-resource#5]
I'd like to be able to `git checkout` my `cf-release` repo to a specific tag so I can access the correct `templates` folder.

**Comment by mariash** [comment]
I believe this is implemented https://github.com/concourse/git-resource#source-configuration

**Comment by fewknow** [comment]
@mariash I am looking for this same functionality but I am not seeing it on the resource.  I have tried `tag_filter` to clone a particular tag when my `- get` is executed for the repository.   I also do not see anything in the documentation for this resource that lets you filter on the "In".   Please advise on how to clone a particular tag.
