### ISSUE TITLE
source.uri is case-sensitive

### ISSUE THREAD

**Issue by cjcjameson** [concourse/git-resource#51]
We have a repo on github under the `Company-ProductGroup` org name, let's call it `Company-ProductGroup/instrumentation`

When we wrote and tried to use a pipeline with the source.uri value of `git@github.com:company-productgroup/instrumentation.git`, the git clone failed. Correcting the capitalization of the org name let things carry on correctly.

We would expect that github org names are not case-sensitive.

**Comment by vito** [comment]
This has nothing to do with us and everything to do with the git server you've pointed it at.
