### ISSUE TITLE
Passing ref to other tasks

### ISSUE THREAD

**Issue by bahmutov** [concourse/git-resource#56]
Hi,

Is there a way to pass the git reference SHA to other tasks in the pipeline?

**Comment by gabro** [comment]
Hi, I'm interested in this as well. I need to use the hash as docker tag and I can't find any documentation.

**Comment by vito** [comment]
At the moment you're on your own; `git rev-parse HEAD` is the usual approach.

We could think about tucking it in some file under `.git`, but I'm not sure I trust `git` to silently ignore it.
