### ISSUE TITLE
Git resource doesn't actually push to git lfs

### ISSUE THREAD

**Issue by zaksoup** [concourse/git-resource#57]
Hi Folks,

I know we (the data toolsmiths) were the folks who originally submitted the LFS PRs to the git resource, but we discovered they don't work! I am creating this issue to track the fact that it still definitely doesn't work, and we (the data toolsmiths) should probably submit some more PRs to actually make LFS work.

Best,
Zak + @cjcjameson

P.S. Do u ever think about space?

**Comment by vito** [comment]
💯

**Comment by oppegard** [comment]
The Pivotal Tracker team is investigating Git LFS for some various use-cases:

- vendoring gems in the event rubygems.org has an outage
- vendoring node_modules if NPM has an outage
- committing the output of `rake assets:precompile`

Does this resource still not support `git push` when using LFS? Also @zaksoup, anything to report on how well LFS works overall?

**Comment by cjcjameson** [comment]
I'm not sure on the `git push` question. Good to investigate.

Overall, we've not had many reports of teams having issues. We also
specifically used it for repos that are used less often. So not sure what
the denominator of "not many reports" is.

**Comment by jama-pivotal** [comment]
@cjcjameson @zaksoup I've gone ahead and closed this issue for now since it's a bit stale. Feel free to enter new issues though if there are some actionable bugs that we can tackle! Thanks
