### ISSUE TITLE
I don't want to use SSH keys, I'd rather give an API token

### ISSUE THREAD

**Issue by jchester** [concourse/git-resource#6]
1. Checking a private key into a repo is sinful in any case.
2. Github API tokens can have permissions limited to pull-only. SSH keys effectively have "root" on everything a user account can push/pull to.

**Comment by jchester** [comment]
Wait, I'm stupid. 

API tokens suck too, no read/write permission separation. Closing.

**Comment by charles-dyfis-net** [comment]
> Wait, I'm stupid.
> 
> API tokens suck too, no read/write permission separation. Closing.

They're experimental, but with github's FGPATs being available this is no longer true; one can have a PAT with only read access to a specific repo while the user who owns it has write, f/e.
