### ISSUE TITLE
Git resource occasionally refuses to connect to repo(s)

### ISSUE THREAD

**Issue by mtpleasantbc** [concourse/git-resource#68]
We are running 1.4.1 and find that randomly, a git resource which has worked fine will refuse to pull from a repo which has new commits available. 

There are no errors, the resource simply spins and never times out.

This is a random issue that affects most of our pipelines which normally work without an issue.

Anyone else experience a similar issue?

**Comment by vito** [comment]
The resource really just does a `git clone` - no magic about it. Sounds like your workers are having network issues?

**Comment by xoebus** [comment]
Does `git` have connect timeout configuration?

**Comment by mtpleasantbc** [comment]
Disregard this, we've traced it to a btrfs lock issue.
