### ISSUE TITLE
Attempts to add a private key with a passphrase for SSH fail silently

### ISSUE THREAD

**Issue by devorbitus** [concourse/git-resource#70]
If you give Concourse an SSH private key that has a passphrase the only error you will see is when you click the resource is something like unable to check. Only experienced _Concoursers_ recognize the missing hashes for a git resource and suggest connectivity problems with the private key. We figured the issue out but I figured I would create an issue in the hopes some kind of relatively simple check can be added to help future devs.

**Comment by chrisburrus** [comment]
I hate to ask, but I've been able to figure out how the SSH keys work in general - I even made an issue of it (https://github.com/concourse/git-resource/issues/65) but it has gone unanswered. Would you be willing to provide an example of the syntax of using an SSH key? It hasn't worked for me at all.

**Comment by vito** [comment]
there are examples in the readme:

https://github.com/concourse/git-resource/blob/master/README.md

**Comment by chrisburrus** [comment]
My apologies, I was referring to HTTPS auth, not SSH, got mixed up in my mind. Sorry about that.

**Comment by vito** [comment]
@devorbitus A helpful error should already show up when looking at the resource page. The box will also turn orange in the pipeline. (Unless it's a `put`, which is a separate bug.)
