### ISSUE TITLE
Continuously update git-lfs binary

### ISSUE THREAD

**Issue by oppegard** [concourse/git-resource#71]
The current `git-lfs` binary is at version 1.1.2, while the latest is at 1.2.1. Should we consider making the [git-lfs github release](https://github.com/github/git-lfs/releases) an explicit input to the [git-resource build plan](https://github.com/concourse/concourse/blob/master/ci/pipelines/resources.yml#L151)?

**Comment by vito** [comment]
Yeah - having that be an explicit input would be great.

**Comment by jtarchie** [comment]
This just becomes a CI concern for the resources pipeline. Watch the binary, update the `Dockerfile`, profit!

**Comment by YoussB** [comment]
well... it's been years 😁. `git lfs` is no longer there.
refs: #248 #250 

closing.
