### ISSUE TITLE
Should the in script reuse the clone maintained by the check script?

### ISSUE THREAD

**Issue by tomwhoiscontrary** [concourse/git-resource#73]
Firstly, i should say that i am still trying to get my head round how this resource works, so i might have the wrong end of the stick here.

This is an idea for an enhancement.

The 'check' script does this:

```bash
destination=$TMPDIR/git-resource-repo-cache

if [ -d $destination ]; then
  cd $destination
  git fetch
  git reset --hard FETCH_HEAD
```

Which means that if the resource container is reused, it will do incremental fetches from the origin into $TMPDIR/git-resource-repo-cache to get new commits.

The 'in' script does this:

```bash
cat > $payload <&0
# ...
uri=$(jq -r '.source.uri // ""' < $payload)
# ...
git clone --single-branch $depthflag $uri $branchflag $destination
```

Which means that it's always pulling a fresh (albeit possibly shallow) clone from the origin.

Would it be possible for the 'in' script to clone from $TMPDIR/git-resource-repo-cache instead? That means the clone would be purely local, and would not need to go out to the network again.

You'd need to make sure it was a standalone clone, not using hardlinks or sharing or whatever, but there are flags for that.

I appreciate that you probably want the clone's remote to be the real origin, not the local cache, but that can be arranged. Perhaps do a clone from the origin with `--depth 0` (is that allowed?) then do a pull from the local cache. Or else clone, then use `git remote` to rewrite the remote. You'd need to do something about tracking branches too.

You'd need to allow for the case where 'in' is asked for a version of the repository which isn't in the cache (say because the resource container was deleted in between the 'check' and the 'in'). You could deal with that by checking to see if the version is there, and if not, calling into the 'check' machinery to create and update the cache.

**Comment by tomwhoiscontrary** [comment]
All this assumes that the check and in scripts run in the same container instance. Or at least instances sharing a filesystem. But they don't, do they?

So there's no way to avoid every run of an 'in' script downloading the whole resource from scratch, right?

**Comment by vito** [comment]
Right. There's also no real guarantee that `check` works by cloning the repo in the first place - generally `check` scripts perform much more lightweight actions for determining whether new versions are available. It so happens that the `git` resource has ~~complicated~~rich enough version discovery semantics that the simplest way for it to work is by doing a `clone`.

A more concrete issue with this would be managing state between the two. There might not even be a `check` container around by the time `get` runs.

So yeah, it's a tempting thing to want at a high level, but the cost, in the of added complexity in the resource interface required to support it, as well as the actual architectural gymnastics needed to implement it, is too high for me.

**Comment by tomwhoiscontrary** [comment]
@vito Thanks for the response. I can totally buy that this is something that isn't worth implementing today.

However ...

If you did want to do something like this, the semantics could be "an operation on a resource may run in a container that has previously been used for another operation on that resource, or may run in a fresh container". So scripts must tolerate running in a fresh container, but may optionally reuse stuff that has already been downloaded. I think that would be easy for resource authors to work with, would allow useful optimisations, and i would think would be quite easy to implement, as it's what you already do for 'check'.

Can i ask a follow-up question? If i have multiple jobs which consume the same version of some resource, goes 'in' always run once for each job, or can the downloaded resource be reused?

**Comment by vito** [comment]
The resource is only fetched once per worker, and a copy-on-write version of it will be provided to the build. This is also ensured for concurrent `get`s that picked the same worker; only one will actually run.

**Comment by tomwhoiscontrary** [comment]
😎 i can work with that.

**Comment by vito** [comment]
:+1:
