### ISSUE TITLE
Tag behaviors should work for detached HEAD tags

### ISSUE THREAD

**Issue by nebhale** [concourse/git-resource#74]
Currently, when specifying a value for `tag_filter` the only candidates that are considered are the ones that are reachable from the specified (or default) branch.  Tags that are detached `HEAD`s (or in other branches) are not considered since they are not retrieved during `git fetch <BRANCH>`.

In Maven (and Java generally) the version of an application exists in source control.  So, when we tag a release, it requires a commit that contains those changes.  In the Spring projects, it’s common that `master` _never has a release on it_.  Version numbers go from one snapshot to another from the perspective of `master`, and the release hangs off and has to be directly targeted.

![screen shot 2016-08-15 at 15 04 34](https://cloud.githubusercontent.com/assets/60754/17717917/be3f4b6e-63c5-11e6-8ef0-5a71d7e9a72f.png)

Based on a [Slack conversation](https://concourseci.slack.com/archives/general/p1471373409005793) I'd like to advocate that any behavior having to do with tags (`tag_filter` is the only one that's obvious to me) ignore branches completely.  All tags, regardless of what they're reachable from `HEAD` or not, should be considered.  This policy should hold true for other future features having to do with tags as well.

**Comment by macropin** [comment]
I think I've hit the same issue from a different angle - we're trying use git tags for docker image tags and the git resource doesn't see pushed tags unless followed by a commit. I believe this is because the git resource only runs `git fetch` not `git fetch --tags` https://github.com/concourse/git-resource/blob/master/assets/check#L37. `git fetch --tags` implies `git fetch` so a one line change should work.

**Comment by ljfranklin** [comment]
Hit this as well when attempting to pull terraform's [v0.8.7 tag](https://github.com/hashicorp/terraform/tree/v0.8.7). While the `check` detected this tag, the subsequent `get` fails with:

```
Cloning into '/tmp/build/get'...
Checking out files: 100% (8552/8552), done.
error: pathspec 'v0.8.7' did not match any file(s) known to git.
```

Hijacking onto the `get` container confirms that this tag is absent, but shows up after running `git fetch --tags` as the tag exists but is not reachable from master. Related [SO answer](http://stackoverflow.com/a/15794719/1437783).

**Comment by Wintermute1** [comment]
@ljfranklin i'm encountering the same issue. The check detects the tag but the get fails. Have you found a way to fix or get around this? Thanks

**Comment by ljfranklin** [comment]
@Wintermute1 I think I ended up just ignoring that tag. If you wanted to take a stab at actually fixing the problem, it _might_ be as easy as adding the `--tags` flag to fetch here: https://github.com/concourse/git-resource/blob/096e9228292cf0342a8b748b8cf34ecc3edb6cc0/assets/in#L63. Haven't tested that though.

**Comment by philwebb** [comment]
I think PR #123 may fix this issue (although it looks like there aren't any tests)

**Comment by youngm** [comment]
Anyone figured out any workarounds for this?

**Comment by talset** [comment]
linked to https://github.com/concourse/git-resource/issues/94

fixed by https://github.com/concourse/git-resource/pull/223

**Comment by goddenrich** [comment]
I think this is now fixed by pr #225 which just got merged

**Comment by vito** [comment]
@goddenrich yep!

**Comment by nebhale** [comment]
Confirmed.

**Comment by vito** [comment]
@nebhale thanks for checking back! :+1:
