### ISSUE TITLE
git-resource not ignoring submodules when using put

### ISSUE THREAD

**Issue by knifhen** [concourse/git-resource#77]
Hi,
We have a pipeline where the get params include a list of submodules that should be cloned. This works fine when checking out the source-code before building. However after building we push a tag back to the repository and this is where the problem occurs.

After the tag is pushed the source-code is pulled again, this time all submodules are cloned. How can we avoid this full submodule clone?

Best regards Andreas Knifh

**Comment by vito** [comment]
`get_params: {submodules: none}` on the `put` step should do it

**Comment by knifhen** [comment]
Thank you so much, that helped.
Is there any official documentation about this get_params? Does it work for all resource types?

**Comment by vito** [comment]
yeah, we just forgot to document it
