### ISSUE TITLE
Clarify supported git url schemes

### ISSUE THREAD

**Issue by sdaschner** [concourse/git-resource#82]
Hi,
first steps with Concourse CI for me, first of all thanks for that great tool with interesting different concepts. :)

I've tried to connect a git-resource to my private git repository (not hosted on github). Is it the case that only the scp-like url scheme `git@...:/path/to/repo.git/` is supported? I've tried several attempts similar to the following ones, but only the last one seems to work (all the others fail with `fatal: Could not read from remote repository.`). I've specified the correct `private_key`, btw.

```
ssh://example.com:1234/path/to/repo.git/
git://example.com:1234/path/to/repo.git/
git@example.com:/path/to/repo.git/
```

The first schemes are needed if you want to specify a different port other than `22`.

Also local directory repositories don't seem to work, neither with `/path/to/repo.git/` nor `file:///path/to/repo.git/`.

Could you please confirm or clarify in the documentation what is supported?

**Comment by vito** [comment]
We just pass it straight through to `git`. I don't think we should document it as that implies there's something weird going on that makes it different.

**Comment by sdaschner** [comment]
I see, but still it didn't work using Concourse. Can you maybe provide another example other than `git@...` -- like a local directory repository -- or actually just confirm that it works on your side?

**Comment by vito** [comment]
Local directories won't work for any resource; they run in their own container. `https://`, `git://`, `git@`, `user@` should all work fine - anything that points to a remote source.

**Comment by sdaschner** [comment]
Oh yeah sure, makes sense for local dirs. I haven't test it for `https://` sources yet, but it didn't work for `ssh://` or `git://` when specified a different port (see original question) -- at least it didn't work in Concourse, but via `git` from the CLI.

**Comment by vito** [comment]
We use `https://` all the time, and we use `git://` in CI, and `ssh://` should be the same as `git@`, assuming you're also configuring a username (`ssh://git@...`) and private key. Maybe it was something wrong with the port? Or maybe it couldn't reach your local network or something?

We pass these values straight through to Git and don't do any parsing ourselves, so beyond the local directory case I don't think there's anything to document.
