### ISSUE TITLE
When configured with depth N, /in should still be able to fetch a ref N+1 commits ago

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/git-resource#85]
The git repository check determines the SHA limited to the paths that are not filtered. When the resource is obtained at getting phase  with depth - the depth is based on the overall repository. This difference results in git failing because the target sha is unrecognizable.

Philosophically speaking since the resource is limited to several paths - the depth parameter in the get operation should be considered as depth for the filtered paths - not the overall repo. Easier said than done, though. There are strategies to obtain the needed depth - check this question for ideas: http://stackoverflow.com/questions/39935546/get-git-sha-depth-on-a-remote-branch/39941969#39941969

Note that since the resource check is cloning the whole repo - if there is a mechanism to store the current depth - it can be used as starting point and this will reduce significantly the number of iterations until it gets to the right one.

As a hot patch, the depth might be ignored - if filters on paths are used ... or it might be reported as an issue when the pipeline validation is made. Note that the connection combining these two will result in "random" failures is hard to make.

**Comment by vito** [comment]
This is unrelated to `paths`. This is a general problem if trying to fetch a commit ~50 commits behind `HEAD` with a `depth` of <50. I don't think the fix should even be related to `paths` as it'll also happen in this general case.

We generally recommend against using `depth` or using a value that's large enough to work "most of the time".

The second recommended approach (doing incremental `git fetch --depth=N+1`) sounds reasonable.

**Comment by jtarchie** [comment]
Let's close this issue. This is one of the pains of using `depth`, which we should not _work around_. We could implement an `N+1` solution, there is a sweet spot where we just end up nulling the usefulness of `depth`.

**Comment by ggeorgiev** [comment]
In my opinion not having such, is what completely nullifies such feature, because it is impossible to use.
