### ISSUE TITLE
Fails to clone private submodules

### ISSUE THREAD

**Issue by TiraO** [concourse/git-resource#87]
It seems that it does not use ssh key to do submodule init. I can clone my repo and its submodules separately (using the same ssh key) and each succeeds, but unless I say `{ submodules: none }` when doing the `get` on the parent, the parent fails to clone with:

```
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/build/get'...
Fetching HEAD
843d29e Rename some concourse stuff
Submodule 'src/main/resources/[redacted]-secrets' (git@[redacted].git) registered for path 'src/main/resources/[redacted]-secrets'
Cloning into '/tmp/build/get/src/main/resources/[redacted]-secrets'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@[redacted].git' into submodule path '/tmp/build/get/src/main/resources/[redacted]-secrets' failed
```

**Comment by vito** [comment]
Does the sub-repo permit that key? One gotcha is with deploy keys, they can only be bound to one repo. You may need to create a CI user that configures the key instead. I'm not sure if there's anything else we can do here; we tried permitting configuration of multiple keys before, but it turned out that `git` just picked the first one that worked, or something like that.

**Comment by TiraO** [comment]
Yep. I am not using a deploy key, I am using a user key, and the user owns both repos.

**Comment by vito** [comment]
Sorry for the delay on this; by now you may have moved on, but just to sanity check, this could easily be a syntax thing. Make sure the key looks like:

```yaml
foo: |
  blah blah blah
```

and *not* something like:

```yaml
foo: |-
  blah blah blah
```

(note the hyphen)

Beyond something like that or a paste error (pasting private keys with vim can go poorly for example) I'm not sure what else would be the issue. We just add the key to the keychain as normal and git clone as normal, so I don't see why it wouldn't work.

**Comment by chendrix** [comment]
This issue has been open for a while and become stale. I'm going to close it now.

**Comment by beeender** [comment]
[Actions](https://github.com/actions) has the same problem, see the discussion https://github.com/actions/checkout/issues/183
