### ISSUE TITLE
"Private keys with passphrases are not supported." for keys with no passphrase

### ISSUE THREAD

**Issue by navicore** [concourse/git-resource#88]
I have a private github repo and am setting `private_key` with a passphrase-less key but am getting error:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
Private keys with passphrases are not supported.
```
<img width="1051" alt="screen shot 2016-10-18 at 3 46 43 pm" src="https://cloud.githubusercontent.com/assets/110999/19499229/1ba0aa18-954a-11e6-928f-c0c85be45753.png">

I'm guessing I'm not setting the private key properly.  Any hints or places to look for errors appreciated.

**Comment by vito** [comment]
Check the formatting of your private key? Maybe it was botched when added to the YAML.

**Comment by navicore** [comment]
sry, got it working with parameters and the cli --var so I'm unblocked.  must have something messed up in my secrets file.

**Comment by rageeth** [comment]
please share what you did to fix it.. i am also facing the same problem

**Comment by petewall** [comment]
I had this problem when I changed my vars file from yaml to JSON.  What mattered to me was this:
The start of the private key begins with a `|` character.  e.g.:
```
  name: source
  source:
    branch: master
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
...
```
And the end of the private key has a newline.

When I had both of those (I was missing the final newline), it worked again.
